#!/bin/sh

# Profile file, runs on login. Environmental variables are set here

# Default programs
export EDITOR=nvim

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Speedy keys
xset r rate 210 40

# Compositor
picom -b
