#!/usr/bin/env bash

sudo rm -rf /usr/local/go

wget -c https://go.dev/dl/go1.24.0.linux-amd64.tar.gz
sudo tar -C /usr/local/ -xzf go1.24.0.linux-amd64.tar.gz
rm -f go1.24.0.linux-amd64.tar.gz

go version
